spring.application.name=VACCINATION_SERVICE
logging.level.com.netflix.discovery=DEBUG
logging.level.org.springframework.cloud.netflix.eureka=DEBUG
spring.cloud.compatibility-verifier.enabled=false
management.endpoints.web.exposure.include=*